name: mergeable

on:
  workflow_call:
    outputs:
      mergeable_state:
        description: "Set to 'clean' if branch is mergeable, otherwise set to 'not_clean'"
        value: ${{ jobs.check_if_branch_is_mergeable.outputs.mergeable_state }}

jobs:
  check_if_branch_is_mergeable:
    name: Check if branch is mergeable
    runs-on: ubuntu-latest
    outputs:
      mergeable_state: ${{ steps.mergeable_check.outputs.mergeable_state }}
    steps:
      - name: Checkout the PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      
      - name: Fetch main branch
        run: |
          git fetch origin main:main

      - name: Check if PR branch contains all commits from main
        id: mergeable_check
        run: |
          if git merge-base --is-ancestor main HEAD; then
            echo "[OK] Selected branch is up-to-date with main and can be merged."
            echo "mergeable_state=clean" >> "$GITHUB_OUTPUT"
          else
            echo "[FAIL] Selected branch is NOT up-to-date with main."
            echo "mergeable_state=not_clean" >> "$GITHUB_OUTPUT"
          fi